add 21. Merge Two Sorted Lists
katsurada1/Leetcode pull request #13
Opened 2022-03-21 14:45 UTC by katsurada1

Please check my code.

2022-04-06 05:04 UTC, kobakobashu requested changes
👀

2022-04-06 05:04 UTC, kobakobashu commented on 21_Merge_Two_Sorted_Lists.py
> +            l2 = l2.next
temp = head = ListNode(0)
l49 -> return head.next

2022-04-06 05:04 UTC, kobakobashu commented on 21_Merge_Two_Sorted_Lists.py
> +#         self.next = next
Please open two lines.

2022-04-06 05:04 UTC, kobakobashu commented on 21_Merge_Two_Sorted_Lists.py
> +        while l1 is not None and l2 is not None:
while l1 and l2

2022-04-06 05:05 UTC, kobakobashu commented on 21_Merge_Two_Sorted_Lists.py
> +        while l1 is not None:
while l1

2022-04-06 14:19 UTC, katsurada1 commented
I am sorry I forgot to correct the code after I was taught on Sunday.
I modified the code.
Please check my code.

2022-04-11 23:26 UTC, kobakobashu commented
LGTM. Please delete the original file and merge only the new one

2022-04-11 23:27 UTC, kobakobashu approved these changes

2022-04-14 12:22 UTC, merged