add 26. Remove Duplicates from Sorted Array
katsurada1/Leetcode pull request #17
Opened 2022-04-01 14:59 UTC by katsurada1

Please check my code.

2022-04-06 05:09 UTC, kobakobashu requested changes
👀

2022-04-06 05:09 UTC, kobakobashu commented on 26.py
> +                n+=1
n += 1

2022-04-06 05:09 UTC, kobakobashu commented on 26.py
> +                nums[n]=nums[i]
nums[n] = nums[i]

2022-04-06 05:09 UTC, kobakobashu commented on 26.py
> +        return(n+1)
return n + 1

2022-04-06 12:44 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-04-11 23:28 UTC, kobakobashu commented
LGTM.
Please delete 21.py and merge only the 26.py

2022-04-11 23:28 UTC, kobakobashu approved these changes

2022-04-14 12:23 UTC, merged