add 27. Remove Element
katsurada1/Leetcode pull request #19
Opened 2022-04-02 12:56 UTC by katsurada1

Please check my code.

2022-04-06 05:09 UTC, kobakobashu requested changes
👀

2022-04-06 05:09 UTC, kobakobashu commented on 27.py
> +        n=0
n = 0

2022-04-06 05:09 UTC, kobakobashu commented on 27.py
> +        for i in nums:
for num in nums

2022-04-06 13:03 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-04-11 23:29 UTC, kobakobashu approved these changes
LGTM

2022-04-14 12:23 UTC, merged