add 28. Implement strStr
katsurada1/Leetcode pull request #21
Opened 2022-04-03 14:00 UTC by katsurada1

Please check my code.

2022-04-06 05:10 UTC, kobakobashu commented
empty file

2022-04-06 13:17 UTC, katsurada1 commented
I am sorry, I had accidentally deleted the file.
Please check my code.

2022-04-06 13:18 UTC, katsurada1 commented
> I am sorry, I had accidentally deleted the file.
> Please check my code.

2022-04-06 13:18 UTC, katsurada1 commented
> empty file

I am sorry, I had accidentally deleted the file.
Please check my code.

2022-04-12 00:16 UTC, kobakobashu requested changes
👀

2022-04-12 00:16 UTC, kobakobashu commented on 28.py
> +        if len(needle) == 0:
if not needle
https://qiita.com/simonritchie/items/bb06a7521ae6560738a7#%E6%9D%A1%E4%BB%B6%E6%96%87%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9

2022-04-12 00:16 UTC, kobakobashu commented on 28.py
> +# n = len(haystack) - len(needle) + 1
n = len(haystack)

2022-04-14 12:33 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-05-17 08:06 UTC, kobakobashu approved these changes
LGTM

2022-05-19 06:42 UTC, merged