add 35. Search Insert Position
katsurada1/Leetcode pull request #23
Opened 2022-04-05 15:08 UTC by katsurada1

Please check my code.

2022-04-12 00:30 UTC, kobakobashu requested changes
Please use PEP8, and you will understand what I mean.
https://note.com/npaka/n/n6afc09f45126

2022-04-12 00:30 UTC, kobakobashu commented on 35.py
> +        r=0
r = 0
https://www.flake8rules.com/rules/E225.html

2022-04-12 00:30 UTC, kobakobashu commented on 35.py
> +        l=len(nums)-1
The variable name "l" is inappropriate
https://www.flake8rules.com/rules/E741.html#:~:text=Variables%20named%20I%20%2C%20O%20%2C%20and,variables%20to%20something%20more%20descriptive.

2022-04-12 00:30 UTC, kobakobashu commented on 35.py
> +# time:O(n)
In a binary search, the search area is halved, so it can be computed in log(n).

2022-04-14 12:42 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-05-17 08:07 UTC, kobakobashu approved these changes
LGTM

2022-05-19 06:42 UTC, merged