add 58. Length of Last Word
katsurada1/Leetcode pull request #26
Opened 2022-04-08 12:19 UTC by katsurada1

Please check my code.

2022-04-12 00:42 UTC, kobakobashu requested changes
👀

2022-04-12 00:42 UTC, kobakobashu commented on 58.py
> +        else:
Good consideration.
However, error handling should be done first.

if not l:
    return 0

return len(l[-1])

2022-04-14 12:46 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-05-17 08:07 UTC, kobakobashu approved these changes
LGTM

2022-05-19 06:42 UTC, merged