add 69. Sqrt
katsurada1/Leetcode pull request #33
Opened 2022-04-14 13:09 UTC by katsurada1

Please check my code.

2022-04-22 09:49 UTC, kobakobashu requested changes
👀

2022-04-22 09:49 UTC, kobakobashu commented on 69.py
> +            if mid * mid <= x < (mid + 1) * (mid + 1):
mid ** 2, (mid + 1) ** 2

2022-04-22 09:49 UTC, kobakobashu commented on 69.py
> +        r = x
what do the s and r mean?

2022-04-29 08:18 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-05-19 06:43 UTC, merged