add 70. Climbing Stairs
katsurada1/Leetcode pull request #35
Opened 2022-04-15 06:09 UTC by katsurada1

Please check my code.

2022-04-22 09:53 UTC, kobakobashu requested changes
👀

2022-04-22 09:53 UTC, kobakobashu commented on 70.py
> +        b = 1
You should name the variables so that you can guess what they mean from their names

2022-04-22 09:53 UTC, kobakobashu commented on 70.py
> +            a, b =b, a + b
= b

2022-05-01 13:26 UTC, katsurada1 commented
I modified the code.
Please check my code.

2022-05-17 08:14 UTC, kobakobashu approved these changes
LGTM

2022-05-19 06:43 UTC, merged